image: node:18-bullseye
variables:
  FF_USE_FASTZIP: "true"

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - web/node_modules/

.pull_cached_node_modules:
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull

stages:
  - setup
  - build

web-setup:
  stage: setup
  script:
    - cd web/
    - npm ci

web-build:
  stage: build
  extends: .pull_cached_node_modules
  needs:
    - web-setup
  script:
    - >-
      export VERSION="{ \"tag\": \"`git describe --tags 2>/dev/null`\", \"branch\": \"$CI_COMMIT_REF_NAME\", \"rev\": \"`git rev-parse --short HEAD 2>/dev/null`\" }"
    - cd web/
    - npm install -g @angular/cli
    - npm install
    - ng build
