services:
  web-build:
    build:
      context: .
      args:
        USER: "${UID}:${GID}"
    container_name: stickers-web-build
    volumes:
      - ./:/app/
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
